### ISSUE TITLE
server:io = io.of("/ssh_"); but where set client io=io("/ssh_");

### ISSUE THREAD

**Issue by hktalent** [billchurch/WebSSH2#127]
server:io = io.of("/ssh_");
but where set client io=io("/ssh_");

```
function mySSH(app, io)
{
    if(!io) io = require('socket.io')(server, { serveClient: false })
    io = io.of("/s_");
    app.use(session);
....
```

**Comment by billchurch** [comment]
I’m not sure I under what you’re saying here

**Comment by hktalent** [comment]
@billchurch 
where the /js/webssh2.bundle.js source,
I want to modify it.
  Io=io("/ssh_");

**Comment by hktalent** [comment]
@billchurch how run ?
```
$ webpack --config  scripts/webpack.common.js
```
thanks

**Comment by hktalent** [comment]
```
app$ webpack -w .
Hash: 686d747c5ec95267178d
Version: webpack 4.28.4
Time: 20129ms
Built at: 01/18/2019 12:47:41 PM
 1 asset
Entrypoint main = main.js
  [6] (webpack)/buildin/global.js 472 bytes {0} [built]
 [55] (webpack)/buildin/module.js 497 bytes {0} [built]
[107] ./server/app.js 4.29 KiB {0} [built]
[198] ./index.js 775 bytes {0} [built]
[266] ./streams (ignored) 15 bytes {0} [built]
[267] ./extend-node (ignored) 15 bytes {0} [built]
[269] util (ignored) 15 bytes {0} [built]
[271] util (ignored) 15 bytes {0} [built]
[305] http (ignored) 15 bytes {0} [built]
[308] ./node_modules/express/lib sync 160 bytes {0} [built]
[341] buffer (ignored) 15 bytes {0} [optional] [built]
[424] ./server/util.js 1010 bytes {0} [built]
[525] ./node_modules/socket.io/lib sync 160 bytes {0} [built]
[526] ./server/socket.js 8.09 KiB {0} [built]
[541] ./server/expressOptions.js 226 bytes {0} [built]
    + 527 hidden modules

WARNING in ./node_modules/socket.io/lib/index.js 113:11-32
Critical dependency: the request of a dependency is an expression
 @ ./server/app.js
 @ ./index.js

WARNING in ./node_modules/express/lib/view.js 81:13-25
Critical dependency: the request of a dependency is an expression
 @ ./node_modules/express/lib/application.js
 @ ./node_modules/express/lib/express.js
 @ ./node_modules/express/index.js
 @ ./server/app.js
 @ ./index.js

WARNING in configuration
The 'mode' option has not been set, webpack will fallback to 'production' for this value. Set 'mode' option to 'development' or 'production' to enable defaults for each environment.
You can also set it to 'none' to disable any default behavior. Learn more: https://webpack.js.org/concepts/mode/

ERROR in ./node_modules/ssh2/lib/agent.js
Module not found: Error: Can't resolve 'child_process' in '/Users/xiatian/Downloads/WebSSH2/app/node_modules/ssh2/lib'
 @ ./node_modules/ssh2/lib/agent.js 6:9-33
 @ ./node_modules/ssh2/lib/client.js
 @ ./server/socket.js
 @ ./server/app.js
 @ ./index.js

ERROR in ./node_modules/ssh2/lib/client.js
Module not found: Error: Can't resolve 'dns' in '/Users/xiatian/Downloads/WebSSH2/app/node_modules/ssh2/lib'
 @ ./node_modules/ssh2/lib/client.js 3:16-30
 @ ./server/socket.js
 @ ./server/app.js
 @ ./index.js

ERROR in ./node_modules/destroy/index.js
Module not found: Error: Can't resolve 'fs' in '/Users/xiatian/Downloads/WebSSH2/app/node_modules/destroy'
 @ ./node_modules/destroy/index.js 14:17-30
 @ ./node_modules/send/index.js
 @ ./node_modules/express/lib/response.js
 @ ./node_modules/express/lib/express.js
 @ ./node_modules/express/index.js
 @ ./server/app.js
 @ ./index.js

ERROR in ./node_modules/etag/index.js
Module not found: Error: Can't resolve 'fs' in '/Users/xiatian/Downloads/WebSSH2/app/node_modules/etag'
 @ ./node_modules/etag/index.js 22:12-25
 @ ./node_modules/express/lib/utils.js
 @ ./node_modules/express/lib/application.js
 @ ./node_modules/express/lib/express.js
 @ ./node_modules/express/index.js
 @ ./server/app.js
 @ ./index.js

ERROR in ./node_modules/express/lib/view.js
Module not found: Error: Can't resolve 'fs' in '/Users/xiatian/Downloads/WebSSH2/app/node_modules/express/lib'
 @ ./node_modules/express/lib/view.js 18:9-22
 @ ./node_modules/express/lib/application.js
 @ ./node_modules/express/lib/express.js
 @ ./node_modules/express/index.js
 @ ./server/app.js
 @ ./index.js

ERROR in ./node_modules/mime/mime.js
Module not found: Error: Can't resolve 'fs' in '/Users/xiatian/Downloads/WebSSH2/app/node_modules/mime'
 @ ./node_modules/mime/mime.js 2:9-22
 @ ./node_modules/send/index.js
 @ ./node_modules/express/lib/response.js
 @ ./node_modules/express/lib/express.js
 @ ./node_modules/express/index.js
 @ ./server/app.js
 @ ./index.js

ERROR in ./node_modules/properties/lib/write.js
Module not found: Error: Can't resolve 'fs' in '/Users/xiatian/Downloads/WebSSH2/app/node_modules/properties/lib'
 @ ./node_modules/properties/lib/write.js 3:9-23
 @ ./node_modules/properties/lib/index.js
 @ ./node_modules/read-config/lib/load/parse/properties.js
 @ ./node_modules/read-config/lib/load/parse/index.js
 @ ./node_modules/read-config/lib/load/merge-parents.js
 @ ./node_modules/read-config/lib/load/index.js
 @ ./node_modules/read-config/lib/read-config.js
 @ ./node_modules/read-config/index.js
 @ ./server/app.js
 @ ./index.js

ERROR in ./node_modules/properties/lib/read.js
Module not found: Error: Can't resolve 'fs' in '/Users/xiatian/Downloads/WebSSH2/app/node_modules/properties/lib'
 @ ./node_modules/properties/lib/read.js 3:9-23
 @ ./node_modules/properties/lib/index.js
 @ ./node_modules/read-config/lib/load/parse/properties.js
 @ ./node_modules/read-config/lib/load/parse/index.js
 @ ./node_modules/read-config/lib/load/merge-parents.js
 @ ./node_modules/read-config/lib/load/index.js
 @ ./node_modules/read-config/lib/read-config.js
 @ ./node_modules/read-config/index.js
 @ ./server/app.js
 @ ./index.js

ERROR in ./node_modules/read-config/lib/read-config.js
Module not found: Error: Can't resolve 'fs' in '/Users/xiatian/Downloads/WebSSH2/app/node_modules/read-config/lib'
 @ ./node_modules/read-config/lib/read-config.js 4:9-22
 @ ./node_modules/read-config/index.js
 @ ./server/app.js
 @ ./index.js

ERROR in ./node_modules/read-config/lib/load/resolve-path.js
Module not found: Error: Can't resolve 'fs' in '/Users/xiatian/Downloads/WebSSH2/app/node_modules/read-config/lib/load'
 @ ./node_modules/read-config/lib/load/resolve-path.js 6:9-22
 @ ./node_modules/read-config/lib/load/merge-parents.js
 @ ./node_modules/read-config/lib/load/index.js
 @ ./node_modules/read-config/lib/read-config.js
 @ ./node_modules/read-config/index.js
 @ ./server/app.js
 @ ./index.js

ERROR in ./node_modules/read-config/lib/load/parse/json5.js
Module not found: Error: Can't resolve 'fs' in '/Users/xiatian/Downloads/WebSSH2/app/node_modules/read-config/lib/load/parse'
 @ ./node_modules/read-config/lib/load/parse/json5.js 5:9-22
 @ ./node_modules/read-config/lib/load/parse/index.js
 @ ./node_modules/read-config/lib/load/merge-parents.js
 @ ./node_modules/read-config/lib/load/index.js
 @ ./node_modules/read-config/lib/read-config.js
 @ ./node_modules/read-config/index.js
 @ ./server/app.js
 @ ./index.js

ERROR in ./node_modules/read-config/lib/load/parse/yaml.js
Module not found: Error: Can't resolve 'fs' in '/Users/xiatian/Downloads/WebSSH2/app/node_modules/read-config/lib/load/parse'
 @ ./node_modules/read-config/lib/load/parse/yaml.js 5:9-22
 @ ./node_modules/read-config/lib/load/parse/index.js
 @ ./node_modules/read-config/lib/load/merge-parents.js
 @ ./node_modules/read-config/lib/load/index.js
 @ ./node_modules/read-config/lib/read-config.js
 @ ./node_modules/read-config/index.js
 @ ./server/app.js
 @ ./index.js

ERROR in ./node_modules/read-config/lib/load/parse/properties.js
Module not found: Error: Can't resolve 'fs' in '/Users/xiatian/Downloads/WebSSH2/app/node_modules/read-config/lib/load/parse'
 @ ./node_modules/read-config/lib/load/parse/properties.js 5:9-22
 @ ./node_modules/read-config/lib/load/parse/index.js
 @ ./node_modules/read-config/lib/load/merge-parents.js
 @ ./node_modules/read-config/lib/load/index.js
 @ ./node_modules/read-config/lib/read-config.js
 @ ./node_modules/read-config/index.js
 @ ./server/app.js
 @ ./index.js

ERROR in ./node_modules/send/index.js
Module not found: Error: Can't resolve 'fs' in '/Users/xiatian/Downloads/WebSSH2/app/node_modules/send'
 @ ./node_modules/send/index.js 23:9-22
 @ ./node_modules/express/lib/response.js
 @ ./node_modules/express/lib/express.js
 @ ./node_modules/express/index.js
 @ ./server/app.js
 @ ./index.js

ERROR in ./node_modules/socket.io/lib/index.js
Module not found: Error: Can't resolve 'fs' in '/Users/xiatian/Downloads/WebSSH2/app/node_modules/socket.io/lib'
 @ ./node_modules/socket.io/lib/index.js 8:11-24 10:13-26
 @ ./server/app.js
 @ ./index.js

ERROR in ./node_modules/ssh2/lib/agent.js
Module not found: Error: Can't resolve 'fs' in '/Users/xiatian/Downloads/WebSSH2/app/node_modules/ssh2/lib'
 @ ./node_modules/ssh2/lib/agent.js 5:9-22
 @ ./node_modules/ssh2/lib/client.js
 @ ./server/socket.js
 @ ./server/app.js
 @ ./index.js

ERROR in ./node_modules/ssh2/node_modules/ssh2-streams/lib/sftp.js
Module not found: Error: Can't resolve 'fs' in '/Users/xiatian/Downloads/WebSSH2/app/node_modules/ssh2/node_modules/ssh2-streams/lib'
 @ ./node_modules/ssh2/node_modules/ssh2-streams/lib/sftp.js 6:16-29 11:9-22
 @ ./node_modules/ssh2/node_modules/ssh2-streams/index.js
 @ ./node_modules/ssh2/lib/client.js
 @ ./server/socket.js
 @ ./server/app.js
 @ ./index.js

ERROR in ./node_modules/express/lib/request.js
Module not found: Error: Can't resolve 'net' in '/Users/xiatian/Downloads/WebSSH2/app/node_modules/express/lib'
 @ ./node_modules/express/lib/request.js 18:11-25
 @ ./node_modules/express/lib/express.js
 @ ./node_modules/express/index.js
 @ ./server/app.js
 @ ./index.js

ERROR in ./node_modules/ssh2/lib/client.js
Module not found: Error: Can't resolve 'net' in '/Users/xiatian/Downloads/WebSSH2/app/node_modules/ssh2/lib'
 @ ./node_modules/ssh2/lib/client.js 2:13-27
 @ ./server/socket.js
 @ ./server/app.js
 @ ./index.js

ERROR in ./node_modules/ssh2/lib/agent.js
Module not found: Error: Can't resolve 'net' in '/Users/xiatian/Downloads/WebSSH2/app/node_modules/ssh2/lib'
 @ ./node_modules/ssh2/lib/agent.js 1:13-27
 @ ./node_modules/ssh2/lib/client.js
 @ ./server/socket.js
 @ ./server/app.js
 @ ./index.js

ERROR in ./node_modules/ssh2/lib/server.js
Module not found: Error: Can't resolve 'net' in '/Users/xiatian/Downloads/WebSSH2/app/node_modules/ssh2/lib'
 @ ./node_modules/ssh2/lib/server.js 1:10-24
 @ ./node_modules/ssh2/lib/client.js
 @ ./server/socket.js
 @ ./server/app.js
 @ ./index.js

ERROR in ./node_modules/engine.io/lib/server.js
Module not found: Error: Can't resolve 'uws' in '/Users/xiatian/Downloads/WebSSH2/app/node_modules/engine.io/lib'
 @ ./node_modules/engine.io/lib/server.js 107:27-41
 @ ./node_modules/engine.io/lib/engine.io.js
 @ ./node_modules/socket.io/lib/index.js
 @ ./server/app.js
 @ ./index.js

```

**Comment by billchurch** [comment]
`npm run build` is what you want. 

You also need to make sure you install the development dependancies uisng `npm install` vs `npm install --production`

What version of NPM/node and what OS/version are you using?

**Comment by billchurch** [comment]
![image](https://user-images.githubusercontent.com/1668075/51386923-2663e700-1af2-11e9-914c-215564a39b5e.png)

**Comment by hktalent** [comment]
@billchurch 
hanks @billchurch
```
my os: kali linux
+ npm@6.6.0
#node -v
v10.12.0
#uname -a
Linux 2cad88573e9d 4.9.125-linuxkit #1 SMP Fri Sep 7 08:20:28 UTC 2018 x86_64 GNU/Linux
#npm i -g webpack
+ webpack@4.28.4
#npm install -D webpack-cli
...
+ webpack-cli@3.2.1

#npm run build
...
Do you want to install 'webpack-cli' (yes/no): yes
..

+ webpack-cli@3.2.1
updated 1 package and audited 1055 packages in 7.769s
found 0 vulnerabilities

{ Error: Cannot find module 'webpack-cli'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:580:15)
    at Function.Module._load (internal/modules/cjs/loader.js:506:25)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at runCommand.then (/root/mytools/node-v10.12.0-linux-x64/lib/node_modules/webpack/bin/webpack.js:142:5)
    at process._tickCallback (internal/process/next_tick.js:68:7) code: 'MODULE_NOT_FOUND' }
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! webssh2@0.2.8 build: `webpack --progress --colors --config scripts/webpack.prod.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the webssh2@0.2.8 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-01-18T15_33_46_076Z-debug.log
```

**Comment by hktalent** [comment]
```
WebSSH2/app#npm i -g webpack@4.0.0
WebSSH2/app#npm run build

> webssh2@0.2.8 build /root/mytools/WebSSH2/app
> webpack --progress --colors --config scripts/webpack.prod.js

The CLI moved into a separate package: webpack-cli.
Please install 'webpack-cli' in addition to webpack itself to use the CLI.
-> When using npm: npm install webpack-cli -D
-> When using yarn: yarn add webpack-cli -D
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! webssh2@0.2.8 build: `webpack --progress --colors --config scripts/webpack.prod.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the webssh2@0.2.8 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-01-18T15_38_42_046Z-debug.log
/mytools/WebSSH2/app#

WebSSH2/app#npm i -g webpack

/root/mytools/node-v10.12.0-linux-x64/bin/webpack -> /root/mytools/node-v10.12.0-linux-x64/lib/node_modules/webpack/bin/webpack.js
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.6 (node_modules/webpack/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.6: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

+ webpack@4.28.4

/WebSSH2/app#npm run build

> webssh2@0.2.8 build /root/mytools/WebSSH2/app
> webpack --progress --colors --config scripts/webpack.prod.js

One CLI for webpack must be installed. These are recommended choices, delivered as separate packages:
 - webpack-cli (https://github.com/webpack/webpack-cli)
   The original webpack full-featured CLI.
We will use "npm" to install the CLI via "npm install -D".
Do you want to install 'webpack-cli' (yes/no): yes
Installing 'webpack-cli' (running 'npm install -D webpack-cli')...

> webpack-cli@3.2.1 postinstall /root/mytools/WebSSH2/app/node_modules/webpack-cli
> lightercollective


     *** Thank you for using webpack-cli! ***

Please consider donating to our open collective
     to help us maintain this package.

  https://opencollective.com/webpack/donate

                    ***

npm WARN webpack-cli@3.2.1 requires a peer of webpack@4.x.x but none is installed. You must install peer dependencies yourself.

+ webpack-cli@3.2.1
updated 1 package and audited 1055 packages in 27.576s
found 0 vulnerabilities

{ Error: Cannot find module 'webpack-cli'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:580:15)
    at Function.Module._load (internal/modules/cjs/loader.js:506:25)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at runCommand.then (/root/mytools/node-v10.12.0-linux-x64/lib/node_modules/webpack/bin/webpack.js:142:5)
    at process._tickCallback (internal/process/next_tick.js:68:7) code: 'MODULE_NOT_FOUND' }
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! webssh2@0.2.8 build: `webpack --progress --colors --config scripts/webpack.prod.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the webssh2@0.2.8 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-01-18T15_41_18_625Z-debug.log


```

**Comment by hktalent** [comment]
@billchurch thanks for you
Can you modify or add api? Support for " io.of"
Or give me an example of this? 
```
var express = require('express'),
server = require('https').createServer(credentials,app);
var io = require('socket.io')(server, {
    secure: bUseHttps,
    autoConnect:true});
io.adapter(redisAdapter({ host: 'localhost', port: 6379 }));

//  webssh
require('./ssh').mySSH(app,io.of("/s_"));
// win rdp
require('./mstsc')(server,io.of("/rdp"));

```

**Comment by hktalent** [comment]
```
/app#npm install --save-dev webpack-cli
app#npm install --save-dev webpack
app#npm install --save-dev webpack-merge
WebSSH2/app#npm install --save-dev uglifyjs-webpack-plugin
app#npm install --save-dev clean-webpack-plugin
app#npm install --save-dev copy-webpack-plugin
app#npm install --save-dev 'extract-text-webpack-plugin'


WebSSH2/app#npm run build
h2@0.2.8 build /root/mytools/WebSSH2/app
> webpack --progress --colors --config scripts/webpack.prod.js

clean-webpack-plugin: /root/mytools/WebSSH2/app/client/public has been removed.
Hash: 2ce2b97a6120a1613d13
Version: webpack 4.28.4
Time: 571ms
Built at: 01/18/2019 11:57:00 PM
 1 asset
Entrypoint webssh2 = webssh2.bundle.js
[0] ./client/src/js/index.js 7.62 KiB {0} [built]

WARNING in configuration
The 'mode' option has not been set, webpack will fallback to 'production' for this value. Set 'mode' option to 'development' or 'production' to enable defaults for each environment.
You can also set it to 'none' to disable any default behavior. Learn more: https://webpack.js.org/concepts/mode/

ERROR in ./client/src/js/index.js
Module not found: Error: Can't resolve '@fortawesome/fontawesome' in '/root/mytools/WebSSH2/app/client/src/js'
 @ ./client/src/js/index.js 8:0-50 15:0-11

ERROR in ./client/src/js/index.js
Module not found: Error: Can't resolve '@fortawesome/fontawesome-free-solid/faBars' in '/root/mytools/WebSSH2/app/client/src/js'
 @ ./client/src/js/index.js 9:0-63 15:24-30

ERROR in ./client/src/js/index.js
Module not found: Error: Can't resolve '@fortawesome/fontawesome-free-solid/faClipboard' in '/root/mytools/WebSSH2/app/client/src/js'
 @ ./client/src/js/index.js 11:0-73 15:32-43

ERROR in ./client/src/js/index.js
Module not found: Error: Can't resolve '@fortawesome/fontawesome-free-solid/faCog' in '/root/mytools/WebSSH2/app/client/src/js'
 @ ./client/src/js/index.js 14:0-61 15:64-69

ERROR in ./client/src/js/index.js
Module not found: Error: Can't resolve '@fortawesome/fontawesome-free-solid/faDownload' in '/root/mytools/WebSSH2/app/client/src/js'
 @ ./client/src/js/index.js 12:0-71 15:45-55

ERROR in ./client/src/js/index.js
Module not found: Error: Can't resolve '@fortawesome/fontawesome-free-solid/faKey' in '/root/mytools/WebSSH2/app/client/src/js'
 @ ./client/src/js/index.js 13:0-61 15:57-62

ERROR in ./client/src/js/index.js
Module not found: Error: Can't resolve 'socket.io-client' in '/root/mytools/WebSSH2/app/client/src/js'
 @ ./client/src/js/index.js 3:0-38 19:3-5

ERROR in ./client/src/js/index.js
Module not found: Error: Can't resolve 'style-loader' in '/root/mytools/WebSSH2/app'
 @ ./client/src/js/index.js 18:0-27

ERROR in ./client/src/js/index.js
Module not found: Error: Can't resolve 'xterm/dist/addons/fit/fit' in '/root/mytools/WebSSH2/app/client/src/js'
 @ ./client/src/js/index.js 5:0-48 20:20-23

ERROR in ./client/src/js/index.js
Module not found: Error: Can't resolve 'xterm/dist/xterm' in '/root/mytools/WebSSH2/app/client/src/js'
 @ ./client/src/js/index.js 4:0-44 20:0-19 29:15-23

ERROR in ./client/src/js/index.js
Module not found: Error: Can't resolve 'xterm/dist/xterm.css' in '/root/mytools/WebSSH2/app/client/src/js'
 @ ./client/src/js/index.js 17:0-31

ERROR in webssh2.bundle.js from UglifyJs
Unexpected token: operator (!) [webssh2.bundle.js:130,15]

ERROR in webssh2.bundle.js from Terser
Unexpected token: operator (!) [webssh2.bundle.js:130,15]
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! webssh2@0.2.8 build: `webpack --progress --colors --config scripts/webpack.prod.js`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the webssh2@0.2.8 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-01-18T15_57_00_293Z-debug.log
```

**Comment by hktalent** [comment]
```
/app#npm install compression-webpack-plugin --save-dev
app#npm install --save-dev mini-css-extract-plugin
app#npm i --save '@fortawesome/fontawesome'
app#npm i --save '@fortawesome/fontawesome-free-solid'
app#npm i --save 'xterm'
app#npm i --save 'xterm' 'socket.io-client' 'style-loader'
app#npm i --save 'css-loader'


/mytools/WebSSH2/app#npm run build

> webssh2@0.2.8 build /root/mytools/WebSSH2/app
> webpack --progress --colors --config scripts/webpack.prod.js

clean-webpack-plugin: /root/mytools/WebSSH2/app/client/public has been removed.
Hash: 76579127c10e800923b7
Version: webpack 4.28.4
Time: 9491ms
Built at: 01/19/2019 12:08:15 AM
            Asset       Size  Chunks                    Chunk Names
       client.htm  669 bytes          [emitted]
      favicon.ico   14.7 KiB          [emitted]
webssh2.bundle.js    320 KiB       0  [emitted]  [big]  webssh2
      webssh2.css   6.38 KiB       0  [emitted]         webssh2
Entrypoint webssh2 [big] = webssh2.bundle.js webssh2.css
[16] (webpack)/buildin/global.js 472 bytes {0} [built]
[55] ws (ignored) 15 bytes {0} [optional] [built]
[58] ./client/src/js/index.js + 1 modules 62.9 KiB {0} [built]
     | ./client/src/js/index.js 7.62 KiB [built]
     |     + 1 hidden module
[64] ./client/src/css/style.css 41 bytes [built]
[65] ./node_modules/css-loader??ref--4-2!./client/src/css/style.css 2.72 KiB [built]
    + 61 hidden modules

WARNING in configuration
The 'mode' option has not been set, webpack will fallback to 'production' for this value. Set 'mode' option to 'development' or 'production' to enable defaults for each environment.
You can also set it to 'none' to disable any default behavior. Learn more: https://webpack.js.org/concepts/mode/

WARNING in asset size limit: The following asset(s) exceed the recommended size limit (244 KiB).
This can impact web performance.
Assets:
  webssh2.bundle.js (320 KiB)

WARNING in entrypoint size limit: The following entrypoint(s) combined asset size exceeds the recommended limit (244 KiB). This can impact web performance.
Entrypoints:
  webssh2 (326 KiB)
      webssh2.bundle.js
      webssh2.css


WARNING in webpack performance recommendations:
You can limit the size of your bundles by using import() or require.ensure to lazy load some parts of your application.
For more info visit https://webpack.js.org/guides/code-splitting/
Child extract-text-webpack-plugin node_modules/extract-text-webpack-plugin/dist node_modules/css-loader/index.js??ref--4-2!client/src/css/style.css:
    Entrypoint undefined = extract-text-webpack-plugin-output-filename
    [0] ./node_modules/css-loader??ref--4-2!./client/src/css/style.css 2.72 KiB {0} [built]
        + 1 hidden module
Child extract-text-webpack-plugin node_modules/extract-text-webpack-plugin/dist node_modules/css-loader/index.js??ref--4-2!node_modules/xterm/dist/xterm.css:
    Entrypoint undefined = extract-text-webpack-plugin-output-filename
       2 modules
/mytools/WebSSH2/app#
```

**Comment by hktalent** [comment]
@billchurch 
```
app#npm run build
```
good,ok
