### ISSUE TITLE
Bug: Invalid IPv6 address in allowedSubnets in config.json results in crash

### ISSUE THREAD

**Issue by billchurch** [billchurch/webssh2#167]
Need to add a catch statement here:

https://github.com/billchurch/webssh2/blob/0.2.10-1/app/server/socket.js#L29

Due to this error:
```
/Users/bill/Documents/webssh2/app/node_modules/ip6addr/ip6addr.js:352
      throw new Error('Invalid argument: <addr>/<prefix> expected');
      ^

Error: Invalid argument: <addr>/<prefix> expected
    at new CIDR (/Users/bill/Documents/webssh2/app/node_modules/ip6addr/ip6addr.js:352:13)
    at Object.createCIDR (/Users/bill/Documents/webssh2/app/node_modules/ip6addr/ip6addr.js:711:12)
    at Matcher.addNetworkClass (/Users/bill/Documents/webssh2/app/node_modules/cidr-matcher/src/Matcher.js:20:24)
    at new Matcher (/Users/bill/Documents/webssh2/app/node_modules/cidr-matcher/src/Matcher.js:15:14)
    at Namespace.socket (/Users/bill/Documents/webssh2/app/server/socket.js:29:19)
    at Namespace.emit (events.js:198:13)
    at Namespace.emit (/Users/bill/Documents/webssh2/app/node_modules/socket.io/lib/namespace.js:213:10)
    at /Users/bill/Documents/webssh2/app/node_modules/socket.io/lib/namespace.js:181:14
    at process._tickCallback (internal/process/next_tick.js:61:11)
```

We should be validating the user input before passing this to CIDRMatcher.

Could use "validator" in app.js for this variable, we'd need to loop through it though. Should add this here:

https://github.com/billchurch/webssh2/blob/e796f9fb5874d6557433f25e8976b7aa58fa8144/app/server/app.js#L157

**Comment by billchurch** [comment]
Validator doesn't have a function that will validate subnets... Going to see about doing a PR.

**Comment by billchurch** [comment]
this seems to work with the most recent version of validator as-is.
