### ISSUE TITLE
can not handle with ssh rsa key

### ISSUE THREAD

**Issue by xiutuo** [billchurch/webssh2#254]
cat config.json | more   (only modified with below cols)  
"user": {
    "name": "root",
    "password": null,
    "privatekey": '/root/.ssh/id_rsa',
    "overridebasic": true
  },

then start webssh2 

npm start & 

[root@updatecenter app]# npm start

webbrowers open URL :  http://10.249.200.200:2222/ssh/host/172.16.21.28

show error: (**(node:9401) UnhandledPromiseRejectionWarning: Error: Cannot parse privateKey: Unsupported key format**)

I can not fix it without your help. thank you!

> webssh2@0.4.0 start /root/test/webssh2-master/app
> node index.js

WebSSH2 service reading config from: /root/test/webssh2-master/app/config.json
WebSSH2 service listening on 0.0.0.0:2222

**(node:9401) UnhandledPromiseRejectionWarning: Error: Cannot parse privateKey: Unsupported key format**

    at Client.connect (/root/test/webssh2-master/app/node_modules/ssh2/lib/client.js:243:13)
    at setupConnection (/root/test/webssh2-master/app/server/socket.js:223:12)
    at Namespace.appSocket (/root/test/webssh2-master/app/server/socket.js:249:3)
    at Namespace.emit (events.js:388:22)
    at Namespace.emitReserved (/root/test/webssh2-master/app/node_modules/socket.io/dist/typed-events.js:56:22)
    at /root/test/webssh2-master/app/node_modules/socket.io/dist/namespace.js:141:26
    at processTicksAndRejections (internal/process/task_queues.js:77:11)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:9401) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:9401) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In t

----------------
# node -v
v14.17.0

# npm -v
6.14.13

# uname -a
Linux updatecenter 3.10.0-1160.25.1.el7.x86_64 #1 SMP Wed Apr 28 21:49:45 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

cat /etc/redhat-release 
CentOS Linux release 7.9.2009 (Core)

# sshd -v

OpenSSH_7.4p1, OpenSSL 1.0.2k-fips  26 Jan 2017

**Comment by fmeschbe** [comment]
`user.privatekey` is the actual private key value not the path to the file.
