### ISSUE TITLE
WebSSH2/index.js:56:93  TypeError: Cannot set property 'port' of undefined

### ISSUE THREAD

**Issue by hktalent** [billchurch/WebSSH2#7]
http://localhost:2222/ssh/host/192.168.10.243?port=22&header=My%20Header&color=red

TypeError: Cannot set property 'port' of undefined
   at /Users/xiatian/safe/node/WebSSH2/index.js:56:93
   at Layer.handle [as handle_request] (/Users/xiatian/safe/node/WebSSH2/node_modules/express/lib/router/layer.js:95:5)
   at next (/Users/xiatian/safe/node/WebSSH2/node_modules/express/lib/router/route.js:131:13)
   at Route.dispatch (/Users/xiatian/safe/node/WebSSH2/node_modules/express/lib/router/route.js:112:3)
   at Layer.handle [as handle_request] (/Users/xiatian/safe/node/WebSSH2/node_modules/express/lib/router/layer.js:95:5)
   at /Users/xiatian/safe/node/WebSSH2/node_modules/express/lib/router/index.js:277:22
   at param (/Users/xiatian/safe/node/WebSSH2/node_modules/express/lib/router/index.js:349:14)
   at param (/Users/xiatian/safe/node/WebSSH2/node_modules/express/lib/router/index.js:365:14)
   at Function.process_params (/Users/xiatian/safe/node/WebSSH2/node_modules/express/lib/router/index.js:410:3)
   at next (/Users/xiatian/safe/node/WebSSH2/node_modules/express/lib/router/index.js:271:10)

**Comment by hktalent** [comment]
# 1.safari

# 2.server: name -a
Linux kali 4.6.0-kali1-amd64 #1 SMP Debian 4.6.4-1kali1 (2016-07-21) x86_64 GNU/Linux

# 3.error
SSH CONNECTION CLOSE - Error: Handshake failed: no matching client->server cipherError: read ECONNRESETError: Handshake failed: no matching client->server cipherError: read ECONNRESET CREDENTIALS
